// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BFormGroup: typeof import('bootstrap-vue-3')['BFormGroup']
    BFormCheckbox: typeof import('bootstrap-vue-3')['BFormCheckbox']
    BFormCheckboxGroup: typeof import('bootstrap-vue-3')['BFormCheckboxGroup']
    BFormInput: typeof import('bootstrap-vue-3')['BFormInput']
    BFormInvalidFeedback: typeof import('bootstrap-vue-3')['BFormInvalidFeedback']
    BFormRadioGroup: typeof import('bootstrap-vue-3')['BFormRadioGroup']
    BFormSelect: typeof import('bootstrap-vue-3')['BFormSelect']
    BFormTextarea: typeof import('bootstrap-vue-3')['BFormTextarea']
    BInputGroup: typeof import('bootstrap-vue-3')['BInputGroup']
    BInputGroupAppend: typeof import('bootstrap-vue-3')['BInputGroupAppend']
    InputTester: typeof import('./src/components/InputTester.vue')['default']
  }
}
