// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BFormGroup: typeof import('bootstrap-vue-next')['BFormGroup']
    BFormCheckbox: typeof import('bootstrap-vue-next')['BFormCheckbox']
    BFormCheckboxGroup: typeof import('bootstrap-vue-next')['BFormCheckboxGroup']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BFormInvalidFeedback: typeof import('bootstrap-vue-next')['BFormInvalidFeedback']
    BFormRadioGroup: typeof import('bootstrap-vue-next')['BFormRadioGroup']
    BFormSelect: typeof import('bootstrap-vue-next')['BFormSelect']
    BFormTextarea: typeof import('bootstrap-vue-next')['BFormTextarea']
    InputTester: typeof import('./src/components/InputTester.vue')['default']
  }
}
